// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    owner,
    balance,
    currency
) VALUES (
    'alice',
    100,
    'USD'
) RETURNING id, owner, balance, currency, created_at
`

func (q *Queries) CreateAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
